# Generated by Django 5.1.6 on 2025-04-30 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('months', models.CharField(max_length=100)),
                ('element', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=100)),
                ('compatibility', models.CharField(max_length=100)),
                ('personalities', models.CharField(max_length=100)),
                ('weakness', models.CharField(max_length=100)),
                ('modalities', models.CharField(max_length=100)),
            ],
        ),
    ]
